language: python

dist: xenial

python:
  - "3.7"

services:
  - docker

addons:
  apt:
    sources:
      - sourceline: ppa:wireguard/wireguard
    packages:
      - wireguard
      - openvswitch-switch

before_install:
  - sudo modprobe wireguard openvswitch

install:
  - pip install -r ./requirements.txt
  - pip install -r ./tests/requirements.txt

script: ./tests/run_test.sh
