---
- name: Add Repository
  shell: |
    echo 'deb http://deb.debian.org/debian/ unstable main' > /etc/apt/sources.list.d/unstable.list
    printf 'Package: *\nPin: release a=unstable\nPin-Priority: 90\n' > /etc/apt/preferences.d/limit-unstable
    apt update

- name: Install WireGuard
  package:
    name: 'wireguard'
    state: present
