---
- name: Create Mobula Directory
  file:
    path: '{{install_dir}}'
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Backup External Interface
  copy:
    content: '{{ext_net | to_json}}'
    dest: '{{install_dir}}/extif.json'
    owner: root
    group: root
    mode: 0600

- name: Copy Mobula Scripts
  copy:
    src: '{{item}}'
    dest: '{{install_dir}}'
    owner: root
    group: root
    mode: 0755
  with_items:
    - 'files/gateway.sh'
    - 'files/ovs_vsctl_wrapper.sh'
    - 'files/run_dns_server.sh'
    - 'files/run_ovs.sh'
    - 'files/start.sh'
    - 'files/wg_quick_wrapper.sh'

- name: Generate Mobula Configuration
  template:
    src: '{{item}}'
    dest: '{{install_dir}}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - 'files/constants.conf'
    - 'files/dnsmasq.conf'
    - 'files/hosts'
    - 'files/network.conf'
    - 'files/resolv.conf'

- name: Generate WireGuard Configuration
  template:
    src: 'files/wireguard.conf'
    dest: '{{install_dir}}/{{wireguard_iface}}.conf'
    owner: root
    group: root
    mode: 0600

- name: Copy Mobula Service
  template:
    src: 'files/mobula.service'
    dest: '/etc/systemd/system'
    owner: root
    group: root
    mode: 0644
