---
- name: Create Mobula Directory
  file:
    path: '{{install_dir}}/{{item.path}}'
    state: directory
    owner: root
    group: root
    mode: '{{item.mode}}'
  when: item.state == 'directory'
  with_filetree: 'files/root'

- name: Backup External Interface
  copy:
    content: '{{ext_net | to_json}}'
    dest: '{{etc_dir}}/extif.json'
    owner: root
    group: root
    mode: 0660

- name: Copy Mobula Files
  template:
    src: '{{item.src}}'
    dest: '{{install_dir}}/{{item.path}}'
    owner: root
    group: root
    mode: '{{item.mode}}'
  when: item.state == 'file'
  with_filetree: 'files/root'

- name: Generate WireGuard Configuration
  template:
    src: 'files/wireguard.conf'
    dest: '{{etc_dir}}/wireguard/{{wireguard_iface}}.conf'
    owner: root
    group: root
    mode: 0660

- name: Copy Mobula Service
  template:
    src: 'files/mobula.service'
    dest: '/etc/systemd/system'
    owner: root
    group: root
    mode: 0644
