---
- name: Create Mobula Directory
  file:
    path: '{{item}}'
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - '{{install_dir}}'
    - '{{install_dir}}/data'

- name: Backup External Interface
  copy:
    content: '{{ext_net | to_json}}'
    dest: '{{install_dir}}/data/extif.json'
    owner: root
    group: root
    mode: 0600

- name: Copy Mobula Scripts
  copy:
    src: '{{item}}'
    dest: '{{install_dir}}'
    owner: root
    group: root
    mode: 0755
  with_items:
    - 'files/gateway.sh'
    - 'files/ovs_vsctl_wrapper.sh'
    - 'files/run_dns_server.sh'
    - 'files/run_ovs.sh'
    - 'files/run_wireguard.sh'
    - 'files/start.sh'

- name: Generate Mobula Configuration
  template:
    src: '{{item}}'
    dest: '{{install_dir}}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - 'files/constants.conf'
    - 'files/network.conf'

- name: Generate Mobula Data
  template:
    src: '{{item}}'
    dest: '{{install_dir}}/data'
    owner: root
    group: root
    mode: 0644
  with_items:
    - 'files/data/dnsmasq.conf'
    - 'files/data/hosts'
    - 'files/data/resolv.conf'

- name: Generate WireGuard Configuration
  template:
    src: 'files/data/wireguard.conf'
    dest: '{{install_dir}}/data/{{wireguard_iface}}.conf'
    owner: root
    group: root
    mode: 0600

- name: Copy Mobula Service
  template:
    src: 'files/mobula.service'
    dest: '/etc/systemd/system'
    owner: root
    group: root
    mode: 0644
