- name: Restart WireGuard
  shell: '{{bin_dir}}/run_wireguard.sh'

- name: List OVS Ports
  shell: '{{bin_dir}}/ovs_vsctl_wrapper.sh list-ports {{ovs_bridge}}'
  register: port_list_result

- name: Clean OVS Tunnels
  shell: '{{bin_dir}}/ovs_vsctl_wrapper.sh del-port {{ovs_bridge}} {{item}}'
  when: item is match(geneve_tunnel_prefix + '*')
  with_items:
    - '{{port_list_result.stdout_lines}}'

- name: Create OVS Tunnels
  shell: >
    {{bin_dir}}/ovs_vsctl_wrapper.sh add-port {{ovs_bridge}}
    {{geneve_tunnel_prefix}}{{hostvars[item].host_id}}
    -- set interface {{geneve_tunnel_prefix}}{{hostvars[item].host_id}} type=geneve
    options:remote_ip={{hostvars[item].host_id | get_wireguard_addr | ipaddr('address')}}
    options:dst_port=6254
    options:key={{geneve_tunnel_key}}
  when: item != inventory_hostname
  with_inventory_hostnames:
    - all

- name: Restart DNS Server
  shell: '{{bin_dir}}/run_dns_server.sh restart'
