---
- name: Generate WireGuard Configuration
  template:
    src: 'templates/wg0.conf'
    dest: '{{install_dir}}/{{wireguard_interface}}.conf'
    owner: root
    group: root
    mode: 0600

- name: Restart WireGuard
  shell: |
    ip netns exec {{namespace_name}} wg-quick down {{install_dir}}/{{wireguard_interface}}.conf
    ip netns exec {{namespace_name}} wg-quick up {{install_dir}}/{{wireguard_interface}}.conf

- name: List OVS Ports
  shell: 'ovs-vsctl list-ports {{ovs_bridge}}'
  register: port_list_result

- name: Clean OVS Tunnels
  openvswitch_port:
    bridge: '{{ovs_bridge}}'
    port: '{{item}}'
    state: 'absent'
  when: item is match(vxlan_tunnel_prefix + '*')
  with_items:
    - '{{port_list_result.stdout_lines}}'

- name: Create OVS Tunnels
  openvswitch_port:
    bridge: '{{ovs_bridge}}'
    port: '{{vxlan_tunnel_prefix}}{{hostvars[item].host_id}}'
    state: 'present'
    set: >
      interface {{vxlan_tunnel_prefix}}{{hostvars[item].host_id}}
      type=vxlan options:remote_ip=10.30.0.{{hostvars[item].host_id}}
  when: item != inventory_hostname
  with_inventory_hostnames:
    - all

- name: Generate DNS Configuration
  template:
    src: '{{item}}'
    dest: '{{install_dir}}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - 'templates/dnsmasq.conf'
    - 'templates/hosts'
    - 'templates/resolv.conf'

- name: Restart DNS Server
  shell: 'ip netns exec {{namespace_name}} {{install_dir}}/run_dns_server.sh'
