---
- include_vars: 'vars/{{ansible_distribution}}.yml'

- name: Generate Network Configuration
  template: 
    src: 'templates/ifcfg-veth_m0'
    dest: '{{network_script_dir}}'
    owner: root
    group: root
    mode: 644

- name: Replace External Network
  template:
    src: 'templates/ifcfg-origin'
    dest: '{{network_script_dir}}/ifcfg-{{ext_net.interface}}'
    backup: yes
    owner: root
    group: root
    mode: 644
