---
- name: Install Packages
  package: 
    name: '{{item}}'
    state: present
  with_items:
    - '{{pkgs_iproute2}}'
    - '{{pkgs_openvswitch}}'
    - '{{pkgs_dnsmasq}}'

- name: Install WireGuard
  include_tasks: 'wireguard/{{ansible_distribution}}.yml'

- name: Enable Services
  systemd:
    name: '{{service_openvswitch}}'
    state: started
    enabled: yes

- name: Create Mobula Directory
  file:
    path: '{{install_dir}}'
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Backup External Interface
  copy:
    content: '{{ext_net | to_json}}'
    dest: '{{install_dir}}/extif.json'
    owner: root
    group: root
    mode: 0644

- name: Copy Mobula Scripts
  copy:
    src: '{{item}}'
    dest: '{{install_dir}}'
    owner: root
    group: root
    mode: 0755
  with_items:
    - 'lib/start.sh'
    - 'lib/gateway.sh'

- name: Generate Mobula Configuration
  template:
    src: '{{item}}'
    dest: '{{install_dir}}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - 'templates/constants.conf'
    - 'templates/network.conf'
    - 'templates/{{wireguard_interface}}.conf'

- name: Try to Remove Old OVS Bridge
  openvswitch_bridge:
    bridge: '{{ovs_bridge}}'
    state: absent
  ignore_errors: yes

- name: Create OVS Bridge
  openvswitch_bridge:
    bridge: '{{ovs_bridge}}'
    set: 'bridge {{ovs_bridge}} stp_enable=true'
    state: present

- name: Attach Interfaces to OVS
  openvswitch_port:
    bridge: '{{ovs_bridge}}'
    port: '{{item}}'
    state: present
  with_items:
    - '{{ovs_access_interface}}'
    - '{{ovs_veth_interface}}'

- name: Setup Network Configuration
  include_tasks: 'networks/{{ansible_distribution}}.yml'

- name: Copy Mobula Service
  template:
    src: 'templates/mobula.service'
    dest: '/etc/systemd/system'
    owner: root
    group: root
    mode: 0644

- name: Enable Mobula Service
  systemd:
    name: 'mobula'
    state: stopped
    enabled: yes

- name: Reboot
  reboot:
