---
- name: Install Packages
  package: 
    name: '{{item}}'
    state: present
  with_items:
    - '{{pkgs_iproute2}}'
    - '{{pkgs_openvswitch}}'
    - '{{pkgs_dnsmasq}}'

- name: Install WireGuard
  include_tasks: 'wireguard/{{ansible_distribution}}.yml'

- name: Enable Mobula Service
  systemd:
    name: 'mobula'
    enabled: yes

- name: Reboot
  reboot:
  when: test is not defined

- name: Reboot Containers (Test)
  local_action: |
    shell docker-compose -f ./tests/docker-compose.yml kill
          docker-compose -f ./tests/docker-compose.yml start
  when: test is defined

- name: Reconnect to Containers (Test)
  wait_for_connection:
    delay: 10
  when: test is defined
