---
- name: Install Packages
  package: 
    name: '{{item}}'
    state: present
  with_items:
    - '{{pkgs_iproute2}}'
    - '{{pkgs_openvswitch}}'
    - '{{pkgs_dnsmasq}}'

- name: Install WireGuard
  include_tasks: 'wireguard/{{ansible_distribution}}.yml'

- name: Enable Mobula Service
  systemd:
    name: 'mobula'
    enabled: yes

- name: Reboot
  reboot:
